In [ ]:
 import pandas as pd
import numpy as np
import plotly.express as px
from google.colab import files

In [ ]:
uploaded=files.upload()
if len(uploaded)!=1:
  print("Please upload only one dataset")
else:
  file=list(uploaded.keys())[0]
  df=pd.read_csv(file)
  print("Dataset loaded successfully")

Saving titanic.csv to titanic.csv
Dataset loaded successfully

In [ ]:
print("DATASET PREVIEW\n")
print("First 5 rows of the dataset: \n")
df.head()

DATASET PREVIEW

First 5 rows of the dataset:

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

In [ ]:
print("Last 5 rows of the dataset: \n")
df.tail()

Last 5 rows of the dataset:

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
886,887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.00,NaN,S
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.00,B42,S
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.45,NaN,S
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.00,C148,C
890,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.75,NaN,Q

In [ ]:
print("The shape of the dataset: \n")
df.shape

The shape of the dataset:

(891, 12)

In [ ]:
print("The features of the dataset are: ")
df.columns.tolist()

The features of the dataset are:

['PassengerId',
 'Survived',
 'Pclass',
 'Name',
 'Sex',
 'Age',
 'SibSp',
 'Parch',
 'Ticket',
 'Fare',
 'Cabin',
 'Embarked']

In [ ]:
print("Data types: ")
df.dtypes

Data types:

PassengerId      int64
Survived         int64
Pclass           int64
Name            object
Sex             object
Age            float64
SibSp            int64
Parch            int64
Ticket          object
Fare           float64
Cabin           object
Embarked        object
dtype: object

In [ ]:
print("MISSING VALUES ANALYSIS \n")
missingValues=df.isnull().sum()
missingValues

MISSING VALUES ANALYSIS

PassengerId      0
Survived         0
Pclass           0
Name             0
Sex              0
Age            177
SibSp            0
Parch            0
Ticket           0
Fare             0
Cabin          687
Embarked         2
dtype: int64

In [ ]:
fig=px.bar(x=missingValues.index,y=missingValues.values,title="Missing values analysis",labels={"x":"Columns","y":"missing values"})
fig.show()

In [ ]:
print("STATISTICAL SUMMARY")
df.describe()

STATISTICAL SUMMARY

,PassengerId,Survived,Pclass,Age,SibSp,Parch,Fare
count,891.000000,891.000000,891.000000,714.000000,891.000000,891.000000,891.000000
mean,446.000000,0.383838,2.308642,29.699118,0.523008,0.381594,32.204208
std,257.353842,0.486592,0.836071,14.526497,1.102743,0.806057,49.693429
min,1.000000,0.000000,1.000000,0.420000,0.000000,0.000000,0.000000
25%,223.500000,0.000000,2.000000,20.125000,0.000000,0.000000,7.910400
50%,446.000000,0.000000,3.000000,28.000000,0.000000,0.000000,14.454200
75%,668.500000,1.000000,3.000000,38.000000,1.000000,0.000000,31.000000
max,891.000000,1.000000,3.000000,80.000000,8.000000,6.000000,512.329200

In [ ]:
numeric_columns=df.select_dtypes(include=np.number).columns.tolist()
numeric_columns

['PassengerId', 'Survived', 'Pclass', 'Age', 'SibSp', 'Parch', 'Fare']

In [ ]:
import ipywidgets as widgets

In [ ]:
hist_column=widgets.Dropdown(options=numeric_columns,description="Column:")
hist_column

Dropdown(description='Column:', options=('PassengerId', 'Survived', 'Pclass', 'Age', 'SibSp', 'Parch', 'Fare')…

In [ ]:
fig=px.histogram(df,x=hist_column.value,title=f"histogram of {hist_column.value}")
fig.show()

In [ ]:
box_column=widgets.Dropdown(options=numeric_columns,description="Column:")
box_column

Dropdown(description='Column:', options=('PassengerId', 'Survived', 'Pclass', 'Age', 'SibSp', 'Parch', 'Fare')…

In [ ]:
fig=px.box(df,x=box_column.value,title=f"box plot of {box_column.value}")
fig.show()

In [ ]:
x_column=widgets.Dropdown(options=numeric_columns,description="X axis: ")
x_column

Dropdown(description='X axis: ', options=('PassengerId', 'Survived', 'Pclass', 'Age', 'SibSp', 'Parch', 'Fare'…

In [ ]:
y_column=widgets.Dropdown(options=numeric_columns,description="y axis: ")
y_column

Dropdown(description='y axis: ', options=('PassengerId', 'Survived', 'Pclass', 'Age', 'SibSp', 'Parch', 'Fare'…

In [ ]:
fig=px.scatter(df,x=x_column.value,y=y_column.value,title=f"{x_column.value} vs {y_column.value}")
fig.show()

In [ ]:
correlation=df.select_dtypes(include=np.number).corr()
correlation

,PassengerId,Survived,Pclass,Age,SibSp,Parch,Fare
PassengerId,1.000000,-0.005007,-0.035144,0.036847,-0.057527,-0.001652,0.012658
Survived,-0.005007,1.000000,-0.338481,-0.077221,-0.035322,0.081629,0.257307
Pclass,-0.035144,-0.338481,1.000000,-0.369226,0.083081,0.018443,-0.549500
Age,0.036847,-0.077221,-0.369226,1.000000,-0.308247,-0.189119,0.096067
SibSp,-0.057527,-0.035322,0.083081,-0.308247,1.000000,0.414838,0.159651
Parch,-0.001652,0.081629,0.018443,-0.189119,0.414838,1.000000,0.216225
Fare,0.012658,0.257307,-0.549500,0.096067,0.159651,0.216225,1.000000

In [ ]:
fig=px.imshow(correlation,text_auto=True,title="Correlation matrix")
fig.show()